version: '3.8'

services:
  server_test:
    container_name: server_test
    build: .
    command: npm run test
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
    depends_on:
      - db_test
    volumes:
      - .:/app
  db_test:
    container_name: db_test
    build: ./db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
